### ISSUE TITLE
No ability to create test factions for combat testing

### ISSUE THREAD

**Issue by BobTheGimp** [B-iggy/HWS-Creative-Scenario#1]
Love the config, very helpful.
This scenario has no options to create player factions for testing multi vs 1 or multi vs multi combat testing. Is this an simple YAML change fix or does it require more detailed work?
Cheers
Bob

**Comment by B-iggy** [comment]
Thanks for the report @BobTheGimp 
Fixed with commit https://github.com/B-iggy/HWS-Creative-Scenario/commit/b6ed2ea7f24fd912abd2bea97ec84eb320c61b99
